version: '3.8'

services:
  # ProbeOps API service
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: probeops-api:latest
    container_name: probeops-api
    command: ["./start.sh"]
    restart: always
    ports:
      - "${API_PORT:-5000}:5000"
    volumes:
      - ./:/app
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - probeops-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # PostgreSQL database service
  db:
    image: postgres:15-alpine
    container_name: probeops-db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "${DB_PORT:-5432}:5432"
    networks:
      - probeops-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

# Volumes for persistent data
volumes:
  postgres_data:
    name: probeops-postgres-data

# Network for service communication
networks:
  probeops-network:
    name: probeops-network