version: "3.8"

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/probeops
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-4f0e1dc2f5ddd8a2a73c5cdfd1f7a10dc48de6a9f37a942e7eb57e5b614e8201}
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    depends_on:
      - db
    restart: always

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=probeops
    ports:
      - "5432:5432"
    restart: always

volumes:
  postgres_data: