"""Initial migration

Revision ID: 691e893eef87
Revises: 
Create Date: 2025-05-10 09:25:52.565632

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '691e893eef87'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('probe_results', schema=None) as batch_op:
        batch_op.drop_index('ix_probe_results_id')

    op.drop_table('probe_results')
    with op.batch_alter_table('probe_jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_probe_jobs_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_email')
        batch_op.drop_index('ix_users_id')
        batch_op.drop_index('ix_users_username')
        batch_op.create_unique_constraint(None, ['username'])
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('ix_users_username', ['username'], unique=True)
        batch_op.create_index('ix_users_id', ['id'], unique=False)
        batch_op.create_index('ix_users_email', ['email'], unique=True)

    with op.batch_alter_table('probe_jobs', schema=None) as batch_op:
        batch_op.create_index('ix_probe_jobs_id', ['id'], unique=False)

    op.create_table('probe_results',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('result', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['probe_jobs.id'], name='probe_results_job_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='probe_results_pkey')
    )
    with op.batch_alter_table('probe_results', schema=None) as batch_op:
        batch_op.create_index('ix_probe_results_id', ['id'], unique=False)

    # ### end Alembic commands ###
